server:
  port: 8082
spring:
  #application:
    #name: users-subgraph
  graphql:
    path: /graphql
    media-types: application/json
  #datasource:
    #url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  #schema:
    #locations: classpath:graphql/
